# Lembrar de colocar databases
CREATE DATABASE IF NOT EXISTS GATEWAY;
CREATE DATABASE IF NOT EXISTS REPOSITORYBALANCER;
CREATE DATABASE IF NOT EXISTS USERBALANCER;
CREATE DATABASE IF NOT EXISTS CLOUDFTP;
CREATE USER 'ismael'@'localhost' IDENTIFIED BY 'matheus';
GRANT ALL PRIVILEGES ON *.* TO 'ismael'@'%' IDENTIFIED BY 'matheus' WITH GRANT OPTION;
FLUSH PRIVILEGES;