spring:
  application:
    name: repository
  datasource:
    username: ${DB_LOGIN:ismael}
    password: ${DB_PASSWORD:matheus}
    url: ${DB_URL:jdbc:mysql://t1-database:3306/cloudftp}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVER:kafka:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: ${GROUP_ID:0}
    admin:
      auto-create: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 1000MB
      max-request-size: 1000MB

server:
  port: ${PORT:8081}
